version: '1'

services:
  pg:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_PASSWORD: g#hEsPZ)cA#2
      POSTGRES_USER: bookstore
      POSTGRES_DB: bookstore
    ports:
      - '5432:5432'

